### ISSUE TITLE
border-radius doesn't require prefixes

### ISSUE THREAD

**Issue by zlatanvasovic** [twitter-archive/css-flip#9] opened 2014-03-21 18:18 UTC
Currently, there is a support for `-webkit-` and `-moz-` prefixes of `border-radius`, but `border-radius` doesn't require prefixes in any browser.

Why are they still here?

**Comment by ljharb** [comment] 2014-03-21 18:52
It certainly does require prefixes in some browsers - just not in current ones.

I'm fine with making the inclusion of these aliases opt-in or opt-out, but please keep them configurable.

**Comment by zlatanvasovic** [comment] 2014-03-21 18:59
I agree with you @ljharb, they should be configurable.

**Comment by necolas** [comment] 2014-03-21 23:43
Effectively a dupe of #5

**Closed as completed by necolas** 2014-03-21 23:43 UTC

**Comment by zlatanvasovic** [comment] 2014-03-22 08:31
Yes, duplicate.
